name: Itch.io Deploy Workflow

on:
  push: # Trigger on push events for all branches
    branches:
      - '*'
    paths:
      - game/**
  workflow_dispatch: # Manual trigger support

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: game # Ensures all actions run in the "game" directory

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: yarn.lock # Adjusted to match "working-directory"
        env:
          CI: true

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build
        env:
          CI: true

      - name: List build output
        run: ls dist

      - name: Deploy to Itch.io
        uses: tomaskynicky/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: adam-slayyyy # Update to match your Itch.io project slug
          ITCH_USER: tomaskynicky # Update with your Itch.io username
          PACKAGE: dist # Directory where build files are located
